version: '3.8'

services:
  app:
    image: theilich/pm:latest
    container_name: app
    hostname: app
    command: ["./myapp"]
    env_file:
      - ./.env
    expose:
      - "8080"
    networks:
      - app-network

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data          # Use the named volume
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:

volumes:
  caddy_data:
    external: true               # Ensure the volume is external
